### ISSUE TITLE
Altitudes displayed but no sectors drawn

### ISSUE THREAD

**Issue by GitUser275** [dark/faa-mva-kml#5]
Thanks for providing these KML format MVA definitions! 

I downloaded two files for my local area and opened them in Google Earth.  I see the sector altitudes are displayed but I see no sector boundary lines.  Do I need to change a setting in Google Earth or are the files incompatible?

e.g. for file P50_MVA_FUS3_2022.kml
![image](https://github.com/dark/faa-mva-kml/assets/33692670/ab2b37c0-f97a-44e9-b18b-837a22d593b9)

Thanks

**Comment by dark** [comment]
Hi, are you using the desktop version of Google Earth or the web version?

I don't have the desktop version handy, but I checked the web version, and it seemed to work. I imported the KML file via the File menu, and this what I see: 
![ge](https://github.com/dark/faa-mva-kml/assets/86657/37c66cf1-6cd0-4935-b736-cf971bde32bc)
Note how, on the bottom left, there's different polygons. Maybe they are not displayed by default in the version you use?

**Comment by GitUser275** [comment]
Hi Marco,

Thanks for the reply.

I'm using GE pro on a Win 8.1 64 bit machine.

![image](https://github.com/dark/faa-mva-kml/assets/33692670/220d18cb-e763-4f39-96fb-b91e38de907a)



I'm willing to edit the KML files if I know what changes are needed.

Thanks,

**Comment by dark** [comment]
So, I downloaded the same version of GE pro, and I opened the same KML with File > Open. It seems to work for me:

![a](https://github.com/dark/faa-mva-kml/assets/86657/3c42d6cf-27fb-44c5-9875-086486ceb21b)

Can you check a couple of things on your end?

- On the upper left side, under Temporary Places, do you see all polygons and all placemarks? Are they all selected, like in my picture?
- If you don't see any polygons, what do you see instead?
- If you see some polygons, can you right click on one of them, check "Properties", and paste here the contents of the various tabs?
- What happens if you try and create a new polygon on your own? To do that, click the "Add Polygon" button at the top and, while the "New Polygon" window is open, click a few times on the map to draw any shape. Does it work? (If it's transparent, check the "Style, Color" tab in the "Add Polygon" window - see picture below).

![b](https://github.com/dark/faa-mva-kml/assets/86657/b27ad392-608e-45cf-80cc-1a42b72c409b)

**Comment by GitUser275** [comment]
I did some experimenting with altitude properties and I'm not convinced GE is a good application for dislaying these MVA KML files.  They would probably be more useful on a flat map but I'm so used to displaying KML flight tracks on GE that it was the app I chose.

Of the properties I experimented with the best result seemed to be as follows:
Select Altitude - "Absolute"
Set altitude to the sector MVA
Select "Extend sides to ground"

This displays a sector with the top at MVA and walls between sectors that make the display meaningful when view is "tilted".   It's still not as good as a flap map presentation and probably not worth pursuing.

**Comment by dark** [comment]
I see what you mean. All airspace polygons are drawn with a coordinate `z = 0` right now, mostly due to laziness on my part. It's possible that, with your default settings, the terrain clips them somehow.
It would be interesting to experiment with a 3d visualization of airspaces, e.g. to visually represent the actual terrain or obstacle clearance, by mirroring the settings that worked for you (that make sense in hindsight).
I have some ideas about how to achieve that; it should be easy. I will experiment in the next few days. If that solution does not create problems when building the Foreflight contentpacks, I will just rebuild all KMLs that way.
I will keep you posted.

**Comment by dark** [comment]
I experimented a little bit with that solution, and I think it makes for better KMLs anyway.
I have updated all KMLs to display the airspaces in 3d. Can you please download the new version and see if that works for you out of the box?

**Comment by GitUser275** [comment]
I downloaded and displayed P50_MVA_FUS3_2022.kml.  Sectors were displayed with tops at MVA and sides extending to ground level..  I saw no intrusion of terrain in any of the sectors I looked at.  Depiction was easy to interpret when viewed from overhead and when tilted.

Thanks for making the change and I hope it does not impact the primary use for display using Foreflight.

**Comment by dark** [comment]
Glad to hear it works.
I tested the new output in ForeFlight, and I could not see any difference. After all, the ForeFlight map is flat.
If someone notices an issue, hopefully they will let us know.
